package functions

// registerMathFuncs registers math function aliases.
func (r *FunctionAliasRegistry) registerMathFuncs() {
	aliases := []*FunctionAlias{
		{PostgreSQLName: "abs", DuckDBName: "abs", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Absolute value"},
		{PostgreSQLName: "ceil", DuckDBName: "ceil", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Ceiling"},
		{PostgreSQLName: "ceiling", DuckDBName: "ceil", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Ceiling"},
		{PostgreSQLName: "floor", DuckDBName: "floor", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Floor"},
		{PostgreSQLName: "round", DuckDBName: "round", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 2, Description: "Round to nearest integer or decimal places"},
		{PostgreSQLName: "trunc", DuckDBName: "trunc", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 2, Description: "Truncate toward zero"},
		{PostgreSQLName: "truncate", DuckDBName: "trunc", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 2, Description: "Truncate toward zero"},
		{PostgreSQLName: "mod", DuckDBName: "mod", Category: DirectAlias,
			MinArgs: 2, MaxArgs: 2, Description: "Modulo"},
		{PostgreSQLName: "power", DuckDBName: "pow", Category: DirectAlias,
			MinArgs: 2, MaxArgs: 2, Description: "Power"},
		{PostgreSQLName: "pow", DuckDBName: "pow", Category: DirectAlias,
			MinArgs: 2, MaxArgs: 2, Description: "Power"},
		{PostgreSQLName: "sqrt", DuckDBName: "sqrt", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Square root"},
		{PostgreSQLName: "cbrt", DuckDBName: "cbrt", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Cube root"},
		{PostgreSQLName: "exp", DuckDBName: "exp", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Exponential"},
		{PostgreSQLName: "ln", DuckDBName: "ln", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Natural logarithm"},
		{PostgreSQLName: "log", DuckDBName: "log", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 2, Description: "Logarithm"},
		{PostgreSQLName: "log10", DuckDBName: "log10", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Base 10 logarithm"},
		{PostgreSQLName: "sign", DuckDBName: "sign", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Sign of number"},
		{PostgreSQLName: "random", DuckDBName: "random", Category: DirectAlias,
			MinArgs: 0, MaxArgs: 0, Description: "Random value between 0 and 1"},
		{PostgreSQLName: "setseed", DuckDBName: "setseed", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Sets random seed"},
		{PostgreSQLName: "pi", DuckDBName: "pi", Category: DirectAlias,
			MinArgs: 0, MaxArgs: 0, Description: "Returns pi constant"},
		{PostgreSQLName: "degrees", DuckDBName: "degrees", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Converts radians to degrees"},
		{PostgreSQLName: "radians", DuckDBName: "radians", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Converts degrees to radians"},
		{PostgreSQLName: "sin", DuckDBName: "sin", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Sine"},
		{PostgreSQLName: "cos", DuckDBName: "cos", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Cosine"},
		{PostgreSQLName: "tan", DuckDBName: "tan", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Tangent"},
		{PostgreSQLName: "cot", DuckDBName: "cot", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Cotangent"},
		{PostgreSQLName: "asin", DuckDBName: "asin", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Arc sine"},
		{PostgreSQLName: "acos", DuckDBName: "acos", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Arc cosine"},
		{PostgreSQLName: "atan", DuckDBName: "atan", Category: DirectAlias,
			MinArgs: 1, MaxArgs: 1, Description: "Arc tangent"},
		{PostgreSQLName: "atan2", DuckDBName: "atan2", Category: DirectAlias,
			MinArgs: 2, MaxArgs: 2, Description: "Arc tangent of two arguments"},
		{PostgreSQLName: "gcd", DuckDBName: "gcd", Category: DirectAlias,
			MinArgs: 2, MaxArgs: 2, Description: "Greatest common divisor"},
		{PostgreSQLName: "lcm", DuckDBName: "lcm", Category: DirectAlias,
			MinArgs: 2, MaxArgs: 2, Description: "Least common multiple"},
	}

	for _, alias := range aliases {
		r.Register(alias)
	}
}
